### ISSUE TITLE
Plugin breaks the new Canvas video player

### ISSUE THREAD

**Issue by mdcanham** [ChineseElectricPanda/canvas-video-enhancer#4]
The new Canvas video player will not play when this plugin is enabled. By disabling this plugin the video player works as normal.

**Comment by ChineseElectricPanda** [comment]
This should have been fixed in v0.1.1.2, commit a14efd82cabc404db63d43f4f19e2712acf3a77a. Can you check that you are on the latest version? Thanks.

**Comment by mdcanham** [comment]
I can confirm that this is fixed in the new version. Chrome did not give me an easy way to update the plugin though. I had to uninstall and reinstall it.

**Comment by ChineseElectricPanda** [comment]
Yeah, Chrome's auto update for extensions is a bit inconsistent, but it should propagate to everyone within a couple of days at most.
